### ISSUE TITLE
Using Infinite Craft website API instead of local AI or ChatGPT to generate item name

### ISSUE THREAD

**Issue by StellarLis** [Spiralio/infinicraft#14]
Infinite Craft website (https://neal.fun/infinite-craft/) sends a request to its API when combining two items.
![Screenshot](https://github.com/user-attachments/assets/70f4cb54-907c-4cb7-b17a-53fda962b3c8)

So, this mod can just send a request to that API and get item name, it's free and you don't need a token or local AI instance.

**Comment by shrimp-alfredo** [comment]
im pretty sure sometimes it redirects to not allowed

**Comment by NonzeroCornet** [comment]
We can't do this due to the fact we need more information about the new item than just a name. Is it edible? Can you throw it? (eventually) Can it be placed? That API only returns a name/emoji.

**Comment by shrimp-alfredo** [comment]
use a mixture of both chatgpt and neal api

**Comment by StellarLis** [comment]
Yeah, after a couple of tests, I've found out that this endpoint sometimes sends 4xx status code.
