### ISSUE TITLE
Question regarding Ollama bridge

### ISSUE THREAD

**Issue by lolo45654** [Spiralio/infinicraft#16]
Ollama has an [OpenAI compatibility layer](https://github.com/ollama/ollama/blob/main/docs/openai.md), is it too experimental to use? It worked for me when I set the API base to `http://localhost:11434/v1`. I'm just confused.

**Comment by NonzeroCornet** [comment]
I'm not sure what your question is. If you are encountering a problem, try updating to the latest version (including the python scripts) and try again.

**Comment by lolo45654** [comment]
I was just wondering why the Ollama bridge exists; that's all.

**Comment by NonzeroCornet** [comment]
Depending on the way the user has set up Ollama, it actually can't be accessed by the mod directly (mainly if they set it up on WSL instead of a direct installation). The bridge ensures complete compatibility,

**Comment by lolo45654** [comment]
Thanks!
